# This is a TOML layout sheet example
[[layouts]]
selector = "main_room"             # 匹配id的正则表达式
size = "10m 10m 10m"
# pos = "0 0 0" # root space 不需要pos
flex_direction = "z" # 按照z轴从下到上排列


[[layouts]]
selector = "table_area"
space_size = "Auto Auto Auto" # 根据实际内容设置
pos = "min min min"

[[layouts]]
selector = "table"
space_size = ["Auto", "Auto", "Auto"] # 根据实际内容设置
pos_x = "min" # 放置在左下角
pos_y = "min"
pos_z = "min"

[[layouts]]
selector = "on_table"
space_size = ["Auto", "Auto", "Auto"] # 根据实际内容设置
pos_x = "min" # 放置在左下角
pos_y = "min"
pos_z = "min"